# Generated by Django 5.0 on 2024-01-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('price', models.IntegerField(max_length=200)),
                ('image1', models.ImageField(upload_to='gallery')),
                ('image2', models.ImageField(upload_to='gallery')),
                ('image3', models.ImageField(upload_to='gallery')),
                ('color', models.CharField(max_length=200)),
                ('material', models.CharField(max_length=200)),
            ],
        ),
    ]
